version: '3.8'
services:
  db:
    image: postgres:15
    container_name: kanban-db
    restart: always
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
      POSTGRES_DB: kanban_db
    ports:
      - '5433:5432'
    volumes:
      - kanban_pgdata:/var/lib/postgresql/data
    networks:
      - kanban-net

volumes:
  kanban_pgdata:

networks:
  kanban-net:
    driver: bridge 